spring.jpa.defer-datasource-initialization=true
spring.application.name=multibrand

# Configuración de la Base de Datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:multibranddb;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar la consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Inicialización de scripts
spring.sql.init.mode=always

# Mostrar las queries generadas por consola con el objetivo de auditar
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true